version: "3.7"

services:
  app:
    image: lifzzz/simplezat:stable
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: ./entrypoint.dev.sh
