version: "3.3"

services:
  nginx:
    image:lifzzz/simplezat-nginx:stable
    ports:
      - "8000:80"
    volumes:
      - app-staticfiles:/app/static

  db:
    image: postgres:11.1-alpine
    volumes:
      - postgres-data:/var/lib/postgressql/data

  app:
    image: lifzzz/simplezat:stable
    volumes:
      - app-staticfiles:/app/static
    command: ./entrypoint.dev.sh

volumes:
  postgres-data:
