version: '3.7'

services:
    app:
        image:
        build:
            context:
            dockerfile:
        volumes:
            - .:/app
        ports:
            - 8000:8000
        command: cd simplezat && python manage.py runserver 0.0.0.0:8000