version: "3.7"

services:
  app:
    image: lifzzz/simplezat:live
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: ./entrypoint.production.sh
